version: "3.8"

networks:
  network:
    name: queue_net
    driver: bridge

services:
  nestjs-app:
    container_name: nestjs-app
    build:
      context: .
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    command: sh -c "yarn install && yarn start:dev"
    networks:
      - network
