FROM node:25-alpine3.23 as builder

WORKDIR /app

COPY ["package.json", "yarn.lock", "/app/"]

RUN yarn install

COPY . /app

RUN yarn build

FROM node:25-alpine3.23

WORKDIR /app

USER node

COPY --chown=node --from=builder /app/node_modules node_modules
COPY --chown=node --from=builder /app/dist dist

ENTRYPOINT ["node", "dist/src/main"]