version: "3.8"

networks:
  queue_net:
    external: true

services:
  node-app:
    build:
      #dockerfile: ./docker/node/Dockerfile
      context: .
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    command: sh -c "npm run start:dev"
    networks:
      - queue_net
